### ISSUE TITLE
v1.4.0 introduced breaking changes

### ISSUE THREAD

**Issue by onlyurei** [craigh411/vue-star-rating#14]
Thanks for the continued support and improvements for this useful vue component!

I noticed that v1.4.0 introduced a breaking change for our usage of this component: the [`main` entry in package.json](https://github.com/craigh411/vue-star-rating/blob/9d1a95122d676cd27d9d73b1e44a27c143729c6d/package.json#L5) was changed from `src/star-rating.vue` to `dist/star-rating.min.js`. Our usage of this component is a direct import of the  `src/star-rating.vue` single file component file, this change broke our build and the component using this component failed to render the `<star-rating>` component.

I think this should be considered a breaking change. Along with the CSS class name changes, I think bumping the major version would be more appropriate? i.e. v2.0.0 instead of v1.4.0.

For now I have to change the semver notation of this package from ^1.3.2 to ~1.3.2 to lock it to the 1.3.x version, so that whenever we shrinkwrap again we don't get bumped to v1.4.0.

Cheers.

**Comment by craigh411** [comment]
I did consider this, but because the class names are not documented I thought that adding the changes to the release notes and bumping the minor version was most appropriate . 

I am more concerned though, that the release broke your build. The UMD module was added to remove the requirement for webpack loaders or browserify transforms by exporting `pre-transpiled` code, and the tests I did with both the webpack and browserify vue-cli templates displayed the component correctly, so I'm not sure why it is breaking for you.

 If you can give me some further information about your build process I will look into it, however, the `src/star-rating.vue` file  is still included, so you should be able to add an alias if you require that particular file.

**Comment by onlyurei** [comment]
When I said it broke our build I actually meant the relevant spec test failed in ci. The asset compilation was successful. The spec tests the existence and count of the `<star>` component using the CSS class names in the selector `'.star-rating .pointer.star'` (which also got changed). We use Browserify/Vuiefy with Gulp to build the front-end assets.

Here's the relevant code snippet in our component that uses the imported `<star-rating>` component:

```
<template>
...
    <star-rating v-model="rating" :max-rating="maxRating" :read-only="readOnly" :star-size="25" :padding="5"
                 :show-rating="false" :increment="1" @rating-selected="updateRating"></star-rating>
...
</template>

<script type="text/coffeescript" lang="coffee">
...
    components:
      StarRating: require 'vue-star-rating'
...
</script>
```

**Comment by craigh411** [comment]
Ah OK. I think what I'll do is document the `css` class names so if they change in future it will force me to bump the major version. I'll keep this as `version 1.4`  for now though to avoid further confusion, but this shouldn't happen in future. Thanks for pointing this out.
