### ISSUE TITLE
enhancement: need config parameter min-rating

### ISSUE THREAD

**Issue by franktopel** [craigh411/vue-star-rating#22]
As of now, even with a stepping of 1, it is possible to give a 0-stars rating. Most existing implementations require that the user can vote only between 1 and 5 stars.

It should be possible to configure a minimum rating value. Of course this can be done using the `rating-selected` event handler (like not applying the vote if the value is less than 1 or whatever the user wants as a minimum), but since this will be a standard requirement this should probably be implemented as a config option `min-rating`.

**Comment by craigh411** [comment]
Thanks for the feedback. I've given this a little thought and I'm not sure there is much of a use case for this because it can already be done with `v-model`:

```JavaScript
new Vue({
  el: '#app',
  data: {
    rating: 1
  }
});
```

Here's the JSFiddle: https://jsfiddle.net/k0x9ayws/

Once set to 1 there isn't any way to set it to 0 without writing that implementation yourself and I can't see anybody needing to set a `min-rating` other than 1. I'm going to close this issue because such an implementation could cause conflicts with other props with little benefit to the majority of users.

**Comment by franktopel** [comment]
I just set your example to 0 by clicking to the very leftmost part of the stars.

**Comment by craigh411** [comment]
Ah, OK. That shouldn't happen, it makes no sense to have to click a 1 pixel column to reset the value, I'll get that fixed.

**Comment by craigh411** [comment]
Fixed in version 1.5.0
