### ISSUE TITLE
All stars black in Safari

### ISSUE THREAD

**Issue by tscole** [craigh411/vue-star-rating#51]
Firefox and Chrome correctly show the default colours, but Safari is just rendering all the stars as black

**Comment by Niiitzer** [comment]
Same here ... Did you figure it out ?

**Comment by resu511** [comment]
Hello,

This problem is probably related to your page having **<base href="/">** in its code and its interpretation by Safari.
As stated in some threads about this subject, the workaround is to preprend the current URL of the page before the ID of the **fill** and **filter** attributes, so that it goes from :
**fill: url(#abcdef)** to **fill: url(https://your-page-url.com#abcdef)**

I did those changes and rebuilt the module.
Here is the raw pastebin of what the **star.vue** looks like : https://pastebin.com/X6nK7F2R
The effective modifications are in computed functions **getGradId()** and **getFilterId**.
I joined the **dist** folder created after the build in case you don't want to modify yourself/cba.

[dist.zip](https://github.com/craigh411/vue-star-rating/files/3393219/dist.zip)

**Comment by craigh411** [comment]
I'm unable to replicate this in the most current version on Safari, so I'll close it. Let me know if it still happens and I'll re-open.
