### ISSUE TITLE
Unexpected token: name (AlphaColor) 

### ISSUE THREAD

**Issue by ShaikhahMaasher** [craigh411/vue-star-rating#70]
Environment: macOS Catalina
Webpack version: ^3.8.1

```
ERROR in product-view.4f490b9e92c6f2785126.js from UglifyJs
Unexpected token: name (AlphaColor) [./node_modules/vue-star-rating/dist/VueStarRating.common.js:625,0][product-view.4f490b9e92c6f2785126.js:4694,6]
```
The error produced by WebPack UglifyJs plugin

**Comment by nkawarewebuy** [comment]
Hi.

Is there any update on this?

**Comment by craigh411** [comment]
I'm guessing that your are using an older version of webpack with an uglify plugin that doesn't support ES6 (which the ParseAlpha class is written in). If you can upgrade webpack, that would be the easiest solution as I'm pretty sure this is no longer an issue. 

I haven't messed around with older webpack configs for a while but if you can't upgrade then you might want to check if you have something like this in your webpack config:

```javascript
{
  test: /\.js$/,
  exclude: [/node_modules/],
  loader: ["babel-loader"]
},
```

This tells babel not to transpile `.js` files in the `node_modules` directory, because they are usually transpiled before distribution.  In Vue we tend to package up the components as is, and let `vue-loader` take care of the transpilation, but that only works on `.vue` files, so  it won't apply this to any `.js` files.

I think you should be able to add an `include` for `vue-star-rating` to allow babel to transpile the `ParseAlpha.js` file in the `vue-star-rating` directory, which should hopefully prevent this error being thrown out from Uglify:

  ```javascript
{
    test: /\.js$/,
    exclude: [/node_modules/],
    loader: ["babel-loader"],
    include: [/node_modules\/vue-star-rating/]
 },
```

**Comment by felipelube** [comment]
@ShaikhahMaasher @craigh411 in my case I got it working with the following configuration:

```js
{
  test: /\.js$/,
  loader: 'babel-loader',
  exclude: /node_modules(?!(\/vue-star-rating))/
},
```

@craigh411 I don't know if this could be considered a breaking change, please consider. anyways, thank you for the project!
