### ISSUE TITLE
Alternative to stars?

### ISSUE THREAD

**Issue by AngelinCalu** [craigh411/vue-star-rating#8]
Could I replace the stars with some box with the corresponding number ?
If yes, what is the best way to achieve that? Thanks!

**Comment by craigh411** [comment]
Funny you should mention this, I'm currently working on extending this project to allow customisable rating types, which would allow you to do exactly what you want - and actually for a simply square this will be quite straightforward in the new version. I have now finished the bulk of the work for this,  but I'll be setting up a new repo for it because it will no longer just be `stars`. Hopefully I'll be able to get a first release of this version up at some point this week because it's essentially the same underlying code as this, but with the ability to extend the components.

**Comment by AngelinCalu** [comment]
Great news! Looking forward to see the updated project!

**Comment by craigh411** [comment]
Just an update on this issue. The code is pretty much finished and I've added an entire font-awesome port, so it's possible to use any font-awesome glyph as a rater as well as creating your own. I just need to write the tests, which I'm planning to do on Monday and update the README to show how to extend the component, then hopefully I can get it released.

**Comment by onlyurei** [comment]
@craigh411 thanks for the update on this feature and this great project! If the rating unit (stars, squares, whatever) container can take an array of class names passed from the component props, it will make customization of the shape of the rating unit a breeze - when custom icon font is used, it would be just a matter of passing in the desired css class name defined in the icon font to change the rating unit appearance.

Looking forward to the new package!

**Comment by craigh411** [comment]
The new project is now up and running and can be found at: https://github.com/craigh411/vue-rate-it. It's quite extensive and I still need to doc some of the extensible features, but the components and documentation for rating with stars, hearts, nearly 700 font awesome glyphs and images are complete. You can find the full docs at: https://craigh411.github.io/vue-rate-it.

I will still be maintaining and updating this project as well, so there's no need switch if you're happy with this component.
